#
# Makefile for the linux kernel.
#

# Object file lists.
#wario_config-y   += iomux_config.o
ccflags-y                       := -Os

obj-y   += iomux.o iomux_config.o

iomux-y := ecspi1_iomux_config.o  gpio2_iomux_config.o  gpio5_iomux_config.o  pwm1_iomux_config.o   uart2_iomux_config.o  usdhc1_iomux_config.o  wdog1_iomux_config.o \
audmux_iomux_config.o  epdc_iomux_config.o    gpio3_iomux_config.o  i2c1_iomux_config.o   sjc_iomux_config.o    uart3_iomux_config.o  usdhc2_iomux_config.o                  \
csi_iomux_config.o     gpio1_iomux_config.o   gpio4_iomux_config.o  i2c2_iomux_config.o   uart1_iomux_config.o  uart4_iomux_config.o  usdhc3_iomux_config.o

